name: Build Windows Application

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Build Frontend (React)
          run: |
            cd frontend
            npm install
            npm run build

        # NOUVELLE ÉTAPE CRITIQUE : On déplace l'interface DANS le backend
        - name: Merge Frontend into Backend
          shell: bash
          run: |
            mkdir -p backend/frontend/dist
            cp -r frontend/dist/* backend/frontend/dist/

        - name: Build Backend & Electron (Windows EXE)
          run: |
            cd backend
            npm uninstall bcrypt
            npm install
            npm run build-win
            
        - name: Upload EXE Artifact
          uses: actions/upload-artifact@v4
          with:
            name: Mada-POS-Setup-Windows
            path: backend/release/*.exe
